vim.cmd [[autocmd FileType * set formatoptions-=ro]]
local opt = vim.opt
opt.relativenumber = true
opt.number = true
opt.numberwidth = 2
opt.expandtab = false
opt.tabstop = 4
opt.shiftwidth = 4
opt.wrap = false
opt.cursorline = true
opt.scrolloff = 10
opt.sidescrolloff = 10
opt.ignorecase = true
opt.completeopt = { "menuone", "noselect" }
opt.backup = false
opt.clipboard = "unnamedplus"
opt.cmdheight = 1
opt.conceallevel = 0
opt.hlsearch = true
opt.smartindent = true
opt.splitbelow = true
opt.splitright = true
opt.swapfile = false
opt.termguicolors = true
opt.undofile = true
opt.writebackup = false
opt.signcolumn = "yes"
